### ISSUE TITLE
Error when register extension

### ISSUE THREAD

**Issue by renanvs** [AppsFlyerSDK/AppsFlyerAdobeExtension#3]
Hi, 
our company have a app for both platform iOS/Android

But we receive this logs recently in both platform:

> 2019-11-18 17:14:39.244711-0300 AppName
> 
> [20260:498179] com.appsflyer.adobeextension was registered
> 
> 2019-11-18 17:14:39.244942-0300 AppName[20260:498454] com.appsflyer.adobeextension Shared State listener was registered
> 
> 2019-11-18 17:14:39.245095-0300 AppName[20260:498454] com.appsflyer.adobeextension Analytics Events listener was registered
> 
> 2019-11-18 17:14:39.245270-0300 AppName[20260:498454] com.appsflyer.adobeextension Shared State listener was initialized
> 
> 2019-11-18 17:14:39.245511-0300 AppName[20260:498454] -[AppsFlyerEventListener initWithExtension:]: unrecognized selector sent to instance 0x6000018371b0
> 
> 2019-11-18 17:14:39.267588-0300 AppName[20260:498454] [AdobeExperienceSDK ERROR <com.appsflyer.adobeextension>]: Failed to respond to external listener registration.
> An unknown exception occurred.
> 
> 2019-11-18 17:14:39.267769-0300 AppName[20260:498454] com.appsflyer.adobeextension unexpectedError Error Domain=com.adobemarketingmobile.module_errors Code=0 "(null)"
> 
> 2019-11-18 17:14:39.453881-0300 AppName[20260:498484] com.appsflyer.adobeextension Cannot initilalise AppsFlyer tracking without an appId or devKey
> 
> 2019-11-18 17:14:39.456091-0300 AppName[20260:498459] com.appsflyer.adobeextension Cannot initilalise AppsFlyer tracking without an appId or devKey
> 
> 2019-11-18 17:14:39.458579-0300 AppName[20260:498458] com.appsflyer.adobeextension Cannot initilalise AppsFlyer tracking without an appId or devKey
> 
> 2019-11-18 17:14:39.512423-0300 AppName[20260:498468] com.appsflyer.adobeextension Cannot initilalise AppsFlyer tracking without an appId or devKey

We follow the standard setup:

```
ACPCore.configure(withAppId: "launch-EN4fa4880c106c40dc9a16d7042a3b52f2")
AppsFlyerAdobeExtension.register()
ACPAnalytics.registerExtension()
ACPIdentity.registerExtension()
ACPCampaignClassic.registerExtension()

ACPLifecycle.registerExtension()

ACPCore.start {
	ACPCore.lifecycleStart(nil)
}
```

Had any change?

**Comment by BenjaminAF** [comment]
Hi @renanvs , we did release AppsFlyerAobeExtension 1.0.9 pod recently, the UI component on Launch was also updated to support the changes (Extension v1.0.7).
The version was released on Sunday, when did this issue start happening?

Could you please open a ticket with support@appsflyer.com and include a screenshot of the AppsFlyer Extension as it is configured on Adobe Lunch?
Please mention this thread in the ticket.

Thank you.
